version: '3.7'

services:
    thebackend:
        build:
          context: ./app-backend
          dockerfile: Dockerfile
        # command: python app-backend/app.py run -h 0.0.0.0
        # volumes:
        #   - ./app-backend/:/usr/src/app/
        ports:
          - '5000:5000'
        # env_file:
        #   - ./thebackend/.flaskenv
        networks:
          - db-net

    thefrontend:
        build:
          context: ./app-frontend/
          dockerfile: Dockerfile
        volumes:
          - ./app-frontend/:/usr/src/app
          - /usr/src/app/node_modules
        ports:
          - '3000:3000'
        environment:
          - NODE_ENV=development
        # links:
        #   - thebackend
        depends_on:
          - thebackend
        networks:
          - db-net

networks:
  db-net:
    driver: bridge
