version: '3.7'

services:
  thebackend:
    restart: always
    tty: true
    build:
      context: ./app-backend
      # dockerfile: Dockerfile
    # command: python app-backend/app.py
    volumes:
      - ./app-backend/:/app/
    ports:
      - '5000:5000'
    # env_file:
    #   - ./thebackend/.flaskenv
    networks:
      - db-net

  thefrontend:
    restart: always
    build:
      context: ./app-frontend/
      dockerfile: Dockerfile
    volumes:
      - ./app-frontend/:/app/
    ports:
      - '3000:3000'
    depends_on:
      - thebackend
    # command: npm start
    networks:
      - db-net

networks:
  db-net:
    driver: bridge
