"""empty message

Revision ID: 750b2a06aca8
Revises: 13f7601c33dd
Create Date: 2022-10-27 22:34:00.324338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '750b2a06aca8'
down_revision = '13f7601c33dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('point',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_name', sa.String(), nullable=True),
    sa.Column('latitude_off', sa.Float(), nullable=True),
    sa.Column('longitude_off', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('point')
    # ### end Alembic commands ###
